name: Builder JSON
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          python -m pip install --upgrade pip

      - name: Install eisen latest package
        run: |
          pip install git+
          pip install --upgrade git+https://github.com/eisen-ai/eisen-deploy.git
          pip install --upgrade git+https://github.com/eisen-ai/eisen-cli.git
          pip install --upgrade git+https://github.com/eisen-ai/eisen-extras.git
          pip install --upgrade git+https://github.com/eisen-ai/eisen-core.git

      - name: Build JSON
        run: |
          python generate_builder_json.py

      - name: Authenticate into Google Cloud Platform
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCLOUD_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Deploy JSON
        run: |
          gcloud components install core --quiet
          mv eisen_modules*.json eisen_modules_latest.json
          gsutil cp eisen_modules_latest.json gs://builder.eisen.ai/json