name: Builder JSON Release
on:
  release:
    types: [created]

jobs:
  version-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Authenticate into Google Cloud Platform
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCLOUD_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Get old version file
        run: |
          gsutil cp gs://builder.eisen.ai/json/versions.json ./

      - name: Add new version to version file
        run: |
          export version=$(python3 -c "import eisen; print(eisen.__version__)")
          cat versions.json | jq '["v"+env.version] + . | unique' > new_versions.json
          mv new_versions.json versions.json
          gsutil cp versions.json gs://builder.eisen.ai/json
