name: Builder JSON
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git

      - name: Install eisen latest package
        run: |
          pip install -r requirements.txt

      - name: Build JSON
        run: |
          python generate_builder_json.py

      - name: Authenticate into Google Cloud Platform
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCLOUD_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Deploy JSON
        run: |
          gcloud components install core --quiet
          gsutil cp eisen_modules_*.json gs://builder.eisen.ai/json